# These are supported funding model platforms

github: [eloyhere]                  # GitHub Sponsors

custom:
  - paypal: https://www.paypal.me/eloyhere       # PayPal
  - https://afdian.net/a/eloyhere   # 爱发电
  - https://qr.alipay.com/fkx141120jptujn5durbjb8   # 支付宝收款码链接
